Make docs more readable and fore one Markdown-style
shalb/cluster.dev pull request #85
Opened 2020-08-28 12:49 UTC by MaxymVlasov

2020-08-28 13:41 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| `init_state_bucket` | check if exist and create a storage for terraform state                |
```suggestion
| `init_state_bucket` | checks if the bucket exists and creates a storage for terraform state                |
```

2020-08-28 13:43 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| Function name       | What function should do                                                |
```suggestion
| Function name       | What the function should do                                                |
```

2020-08-28 13:44 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +### 5. Create cleanup function
```suggestion
### 5. Create the cleanup function
```

2020-08-28 13:44 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +Create a functions which deletes:
```suggestion
Create a function that deletes:
```

2020-08-28 13:45 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +### 6. Set cloud provisioner type
```suggestion
### 6. Set the cloud provisioner type
```

2020-08-28 13:46 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +The options on provisioners could different even inside same cloud provider ex: Minikube, EKS, K3s.
```suggestion
The options on provisioners could differ even inside the same cloud provider, ex: Minikube, EKS, K3s.
```

2020-08-28 13:47 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +The required set of functions are next:
```suggestion
The required set of functions is as follows:
```

2020-08-28 13:47 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| `deploy_cluster`     | Deploy kubernetes cluster itself - save result in separate tf-state               |
```suggestion
| `deploy_cluster`     | Deploy kubernetes cluster itself - save result in a separate tf-state               |
```

2020-08-28 13:47 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| Function name        | What function should do                                                           |
```suggestion
| Function name        | What the function should do                                                           |
```

2020-08-28 13:48 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| `pull_kubeconfig`    | Obtain kubeconfig from created cluster to use in next steps with tf/helm          |
```suggestion
| `pull_kubeconfig`    | Obtain kubeconfig from the created cluster to use in the next steps with tf/helm          |
```

2020-08-28 13:51 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| `init_addons`        | Install mandatory kubernetes addons (see next step) - result as separate tf-state |
```suggestion
| `init_addons`        | Install mandatory kubernetes addons (see next step) - write the result as a separate tf-state |
```

2020-08-28 13:54 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +| `deploy_apps`        | Deploy/reconcile other applications from user's repository from defined folder    |
```suggestion
| `deploy_apps`        | Deploy/reconcile other applications from user's repository, from the defined folder    |
```

2020-08-28 13:55 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +Deploy a mandatory addons for cluster (`deploy_apps`):
```suggestion
Deploy mandatory addons for the cluster (`deploy_apps`):
```

2020-08-28 13:55 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +* Ingress Controller to serve traffic inside cluster
```suggestion
* Ingress Controller to serve traffic inside the cluster
```

2020-08-28 13:55 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +* ArgoCD to deploy an applications
```suggestion
* ArgoCD to deploy an application
```

2020-08-28 13:56 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +To test successful build - deploy a sample applications from `/kubernetes/apps/samples/`
```suggestion
To test whether the build is successful, deploy a sample application from `/kubernetes/apps/samples/`.
```

2020-08-28 13:58 UTC, anastyakulyk commented on docs/add-provider-provisioner.md
> +List of options, should be set in [OPTIONS.md](OPTIONS.md).
```suggestion
Set the list of options in [OPTIONS.md](OPTIONS.md).
```

2020-08-28 14:01 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +1. Create admin account in AWS with `Access Key`. See [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html).
```suggestion
1. Create admin account in AWS with `Access Key`. See the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html).
```

2020-08-28 14:02 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +2. Install `aws-cli`. See [AWS documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html).
```suggestion
2. Install `aws-cli`. See the [AWS documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html).
```

2020-08-28 14:05 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +3. Configure `aws-cli`
```suggestion
3. Configure the `AWS-CLI`
```

2020-08-28 14:06 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +    Any region is OK. See [AWS documentation](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-tutorial.html#tutorial-step2).
```suggestion
    Any region is OK. See the [AWS documentation](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-tutorial.html#tutorial-step2).
```

2020-08-28 14:07 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +Copy logs from region `us-east-1`, because global API calls logged in this region.
```suggestion
Copy the logs from region `us-east-1`, because global API calls are logged in this region.
```

2020-08-28 14:08 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +## Parse logs
```suggestion
## Parse the logs
```

2020-08-28 14:08 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +### Copy logs parsing script
```suggestion
### Copy the logs' parsing script
```

2020-08-28 14:09 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +Replace `MY-IP` by your IP address, which used to deploy cluster.
```suggestion
Replace `MY-IP` by your IP address, which is used to deploy the cluster.
```

2020-08-28 14:09 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +### Get API calls with service and request
```suggestion
### Get API calls with the service and request
```

2020-08-28 14:10 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +Replace `MY-IP` by your IP address, which used to deploy cluster.
```suggestion
Replace `MY-IP` by your IP address, which is used to deploy the cluster.
```

2020-08-28 14:11 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +1. Open visual [policy editor](https://console.aws.amazon.com/iam/home?#/policies$new?step=edit) and add needed permissions regarding to output of the [script](../install/aws_logs_parser.py).
```suggestion
1. Open visual [policy editor](https://console.aws.amazon.com/iam/home?#/policies$new?step=edit) and add needed permissions regarding the output of the [script](../install/aws_logs_parser.py).
```

2020-08-28 14:12 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +2. Save new policy time to time if it has many records, to prevent results loss.
```suggestion
2. Save new policy time to time if it has many records, to prevent results from being lost.
```

2020-08-28 14:12 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +3. Check out its JSON version and save it to [aws_policy.json](../install/aws_policy.json)
```suggestion
3. Check out its JSON version and save it to [aws_policy.json](../install/aws_policy.json).
```

2020-08-28 14:14 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +* [Parse logs](#parse-logs)
```suggestion
* [Parse the logs](#parse-the-logs)
```

2020-08-28 14:15 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +  * [Copy logs parsing script](#copy-logs-parsing-script)
```suggestion
  * [Copy the logs' parsing script](#copy-the-logs-parsing-script)
```

2020-08-28 14:16 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +  * [Get API calls with service](#get-api-calls-with-service)
```suggestion
  * [Get API calls with the service](#get-api-calls-with-the-service)
```

2020-08-28 14:16 UTC, anastyakulyk commented on docs/aws-iam-permissions.md
> +  * [Get API calls with service and request](#get-api-calls-with-service-and-request)
```suggestion
  * [Get API calls with the service and request](#get-api-calls-with-the-service-and-request)
```

2020-08-28 14:20 UTC, anastyakulyk requested changes
Please address the spellcheck issues, otherwise LGTM

2020-09-01 15:54 UTC, voatsap approved these changes
Looks fine, lets apply this

2020-09-10 23:03 UTC, merged